development:
   adapter: mysql2
   database: school_management_app 
   username: root
   password: phpmysql
   host: localhost
test:
   adapter: mysql2
   database: school_management_app
   username: root
   password: phpmysql
   host: localhost
production:
   adapter: mysql2
   database: school_management_app
   username: root
   password: phpmysql
   host: localhost